
sudo: true

language: python

python:
    - 2.7

services:
    - postgresql

addons:
    postgreqsl: 10
    apt:
        packages:
            - postgresql-10
            - postgresql-client-10

env:
    global:
        - PGPORT=5433
        - PGUSER=postgres

## Install testing requirements: psycopg2, flake8, and pytest
install:
    - pip install -r tests/requirements.txt

## Setup the test database
before_script:
    - sudo -u postgres psql -c "CREATE USER postgres;"
    - sudo -u postgres psql -c "ALTER USER postgres WITH SUPERUSER;"
    - (cd tests && ./setup-db.sh)

script:
    - flake8 gwlib
    - PYTHONPATH=. pytest tests -v
